
all:
	mpirun -n 4 PISKa -i ebola-model-info-exponential.cka -i ebola-init-CL-info-4.cka  -i ebola-all_obs.cka -p 100 -t 100 -sync-t 1

time:
	time mpirun -n 4 PISKa -i ebola-model-info-exponential.cka -i ebola-init-CL-info-4.cka  -i ebola-all_obs.cka -p 100 -t 100 -sync-t 1

